# Generated by Django 5.0.6 on 2024-07-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_attribute_attributevalue_image_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
