# Generated by Django 5.0.6 on 2024-07-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_remove_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
